Public Class Collo

    Private Sub limpiarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles limpiarButton.Click
        txtAproDingAop2.Clear()
        txtAproDingAop3.Clear()
        txtCantDdAntRFop2.Clear()
        txtCantDdAntRFop3.Clear()
        txtCantDidAntRFop2.Clear()
        txtCantDidAntRFop3.Clear()
        txtCntDimDantRFop2.Clear()
        txtCntDimDantRFop3.Clear()
        txtCodDSit.Clear()
        txtEnDingAop2.Clear()
        txtEnDingAop3.Clear()
        txtEstaDingAop2.Clear()
        txtEstaDingAop3.Clear()
        txtEstRcpObOp2.Clear()
        txtEstRcpObOp3.Clear()
        txtEstSLAop2.Clear()
        txtEstSLAop3.Clear()
        txtFirSLAop2.Clear()
        txtFirSLAop3.Clear()
        txtNomOpCoub.Clear()
        txtNvlRFop2.Clear()
        txtNvlRFop3.Clear()
        txtOprdra2.Clear()
        txtOprdra3.Clear()
        txtNvlTXop2.Clear()
        txtNvlTXop3.Clear()


    End Sub

    Private Sub cancelarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cancelarButton.Click
        txtAproDingAop2.Clear()
        txtAproDingAop3.Clear()
        txtCantDdAntRFop2.Clear()
        txtCantDdAntRFop3.Clear()
        txtCantDidAntRFop2.Clear()
        txtCantDidAntRFop3.Clear()
        txtCntDimDantRFop2.Clear()
        txtCntDimDantRFop3.Clear()
        txtCodDSit.Clear()
        txtEnDingAop2.Clear()
        txtEnDingAop3.Clear()
        txtEstaDingAop2.Clear()
        txtEstaDingAop3.Clear()
        txtEstRcpObOp2.Clear()
        txtEstRcpObOp3.Clear()
        txtEstSLAop2.Clear()
        txtEstSLAop3.Clear()
        txtFirSLAop2.Clear()
        txtFirSLAop3.Clear()
        txtNomOpCoub.Clear()
        txtNvlRFop2.Clear()
        txtNvlRFop3.Clear()
        txtOprdra2.Clear()
        txtOprdra3.Clear()
        txtNvlTXop2.Clear()
        txtNvlTXop3.Clear()

        Me.Close()
    End Sub
End Class