Public Class Permisos

    Private Sub limpiarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles limpiarButton.Click
        txtAltPer.Clear()
        txtAltPermANAC.Clear()
        txtAltPrmdaTt.Clear()
        txtDocDmils4.Clear()
        txtDocDmils5.Clear()
        txtEstDgesDper.Clear()
        txtPermAmb.Clear()
        txtEstDgesDper.Clear()
        txtFactInTram.Clear()
        txtFactOtor.Clear()
        txtHabInTram.Clear()
        txtHabiOtor.Clear()
        txtNumDordMun.Clear()
        txtPermANACinTra.Clear()
        txtPermANACotor.Clear()
        txtPermArql.Clear()
        txtPermDobInTram.Clear()
        txtPermPatri.Clear()
        txtPrmDobOtor.Clear()
        txtProvANNAC.Clear()
        txtProvGstMuni.Clear()
        txtTipDEstPerm.Clear()
    End Sub

    Private Sub cancelarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cancelarButton.Click
        txtAltPer.Clear()
        txtAltPermANAC.Clear()
        txtAltPrmdaTt.Clear()
        txtDocDmils4.Clear()
        txtDocDmils5.Clear()
        txtEstDgesDper.Clear()
        txtPermAmb.Clear()
        txtEstDgesDper.Clear()
        txtFactInTram.Clear()
        txtFactOtor.Clear()
        txtHabInTram.Clear()
        txtHabiOtor.Clear()
        txtNumDordMun.Clear()
        txtPermANACinTra.Clear()
        txtPermANACotor.Clear()
        txtPermArql.Clear()
        txtPermDobInTram.Clear()
        txtPermPatri.Clear()
        txtPrmDobOtor.Clear()
        txtProvANNAC.Clear()
        txtProvGstMuni.Clear()
        txtTipDEstPerm.Clear()

        Me.Close()
    End Sub
End Class