Public Class Sitio

    Private Sub limpiarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles limpiarButton.Click
        txtAccAconstru.Clear()
        txtAcometAconst.Clear()
        txtAltDest.Clear()
        txtAltTot.Clear()
        txtAltuTot.Clear()
        txtAproINGOpAn.Clear()
        txtCanTENNAdis.Clear()
        txtCantYDimAntnasRF.Clear()
        txtCantYDimTX.Clear()
        txtCosTtPs.Clear()
        txtDocDmils6.Clear()
        txtDocDmils7.Clear()
        txtDocDmils8.Clear()
        txtENFact.Clear()
        txtEnvIngOpeANCLA.Clear()
        txtEstaDproEst.Clear()
        txtEstatusMantPrev.Clear()
        txtEstatusSeguroT.Clear()
        txtEstIngOpAncla.Clear()
        txtEstObra.Clear()
        txtEstOKIngTorre.Clear()
        txtEstRpcObrOp.Clear()
        txtEstruct.Clear()
        txtEstruTENNdis.Clear()
        txtEstrUtili.Clear()
        txtEstSueFechImp.Clear()
        txtFchAprCoxCor.Clear()
        txtFechaInformSeg.Clear()
        txtFran1D.Clear()
        txtFran2D.Clear()
        txtFran3D.Clear()
        txtFunda.Clear()
        txtFundacns.Clear()
        txtipoDestIst.Clear()
        txtMensuFePla.Clear()
        txtNivlDapoEs.Clear()
        txtNivlRFoperANCLA.Clear()
        txtNivTXOperAncla.Clear()
        txtProvDobras.Clear()
        txtProvEstru.Clear()
        txtSitDconfl.Clear()
        txtstructra.Clear()
        txtSupDobras.Clear()
        txtSuperfConst.Clear()
        txtTipoAcceso.Clear()
        txtUtApxLcorp.Clear()

    End Sub

    Private Sub cancelarButton_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles cancelarButton.Click
        txtAccAconstru.Clear()
        txtAcometAconst.Clear()
        txtAltDest.Clear()
        txtAltTot.Clear()
        txtAltuTot.Clear()
        txtAproINGOpAn.Clear()
        txtCanTENNAdis.Clear()
        txtCantYDimAntnasRF.Clear()
        txtCantYDimTX.Clear()
        txtCosTtPs.Clear()
        txtDocDmils6.Clear()
        txtDocDmils7.Clear()
        txtDocDmils8.Clear()
        txtENFact.Clear()
        txtEnvIngOpeANCLA.Clear()
        txtEstaDproEst.Clear()
        txtEstatusMantPrev.Clear()
        txtEstatusSeguroT.Clear()
        txtEstIngOpAncla.Clear()
        txtEstObra.Clear()
        txtEstOKIngTorre.Clear()
        txtEstRpcObrOp.Clear()
        txtEstruct.Clear()
        txtEstruTENNdis.Clear()
        txtEstrUtili.Clear()
        txtEstSueFechImp.Clear()
        txtFchAprCoxCor.Clear()
        txtFechaInformSeg.Clear()
        txtFran1D.Clear()
        txtFran2D.Clear()
        txtFran3D.Clear()
        txtFunda.Clear()
        txtFundacns.Clear()
        txtipoDestIst.Clear()
        txtMensuFePla.Clear()
        txtNivlDapoEs.Clear()
        txtNivlRFoperANCLA.Clear()
        txtNivTXOperAncla.Clear()
        txtProvDobras.Clear()
        txtProvEstru.Clear()
        txtSitDconfl.Clear()
        txtstructra.Clear()
        txtSupDobras.Clear()
        txtSuperfConst.Clear()
        txtTipoAcceso.Clear()
        txtUtApxLcorp.Clear()

        Me.Close()
    End Sub
End Class